import 'semantic-ui-css/semantic.min.css'
import "@/scss/global.scss";
import { Inter } from 'next/font/google'
import { AuthProvider } from '@/contexts';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'francisco',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
