'use client';
import { Inter } from 'next/font/google'
import { Container } from 'semantic-ui-react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'francisco',
  description: 'Generated by create next app',
}

export default function HomeLayout({ children, isOpenSeach = false, isContainer=false, relative=false }) {
  return (
    <>
      {/* TODO: TOP BAR */}
      <Container fluid>
        {isContainer ? <Container fluid>children</Container>:children }
      </Container>
      {/* TODO: FOOTER */}
    </>
  )
}
